spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mundobancario?serverTimezone=UTC
    username: root
    password: 1234  
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: pabloaguilarmartinez96@gmail.com
    password: jsxbgqnyznwqqjpr
    properties:
      mail.smtp.starttls.enable: true  
      mail.smtp.starttls.required: true
      mail.smtp.auth: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
server:
  port: 8080
